Добавляет разметку для Главной и Каталога
htmlacademy-htmlcss/1999403-sedona-33 pull request #2
Opened 2022-01-27 13:57 UTC by igorsokoltsov

2022-01-27 19:56 UTC, andreysgra requested changes
В целом с заданием справились хорошо, но тем не менее есть над чем поработать.

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +          </ul>
Дочерним элементом списка может быть только `<li>`. Перенесите этот список в первый `li` списка `reasons-list`.

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +            <a class="navigation-link navigation-link-current" href="main.html"
Файл главной страницы имеет название **index.html**, а не main.html.

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +            <a class="navigation-link" href="about-sedona.html">О Седоне</a>
Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>`.

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +              <img class="advantages-icon" src="" alt="Жилье" />
Это декоративные изображения:

![image](https://user-images.githubusercontent.com/17790771/151431767-368e6330-9b3d-4170-8968-c189ea70e012.png)

следовательно в разметке они не нужны (будут отображаться с помощью CSS). [Как отличить контентное изображение от декоративного](https://htmlacademy.ru/blog/boost/frontend/content-or-decor-img).

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +        <p>Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!</p>
Нужно соблюсти иерархию заголовков. У вас есть заголовок первого уровня `<h1 class="visually-hidden">Welcome to the gorgeous Sedona</h1>`, а дальше, в списке перечисления причин идут заголовки третьего уровня. Второго уровня нет.

Посмотрим на текст "Рассмотрим 5 причин, по которым Седона круче чем Гранд каньон!". Подходит он на роль заголовка? Да. Потому что внизу идёт перечисление тех самых причин. Значит меняем в разметке параграф на заголовок второго уровня: `<h2 class="main-title">Рассмотрим 5 причин, по которым Седона круче чем Гранд каньон!</h2>`.

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +              <h3 class="advantages-title">Сувениры</h3>
Так как этот список вложенный, то заголовки в нём не могут быть третьего уровня, потому что выше есть `h3`. Значит нужно изменить здесь `h3` на `h4`.

Чтобы лучше понять иерархию заголовков можно провести сравнение с книгой: `h1` - название книги, `h2` - название раздела, `h3` - название главы, `h4` - название части главы. Более низкое дробление, под `h5` и `h6` придумать сложно.

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +        <input type="submit" name="subscribe" value="Подписаться" />
1. `<input type="text">` и `<input type="submit>"` элементы формы. Без формы, сами по себе, они не имеют особого смысла. По формам есть [тренажёр](https://up.htmlacademy.ru/htmlcss/33/module/2/item/6). Также можно посмотреть разметку формы в [этом демо](https://up.htmlacademy.ru/htmlcss/33/demos/6169#37).
2. Вместо `<input type="submit"` лучше использовать `<button type="submit">`, так как `<input type="submit"` устаревший тег.

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +        <b class="footer-contact-phone">+7 (812) 812-12-12</b>
Это не тег `b`, а ссылка в формате `tel`. Подробнее [здесь](https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-03).

2022-01-27 19:56 UTC, andreysgra commented on index.html
> +      </section>
Секция, это достаточно крупный смысловой блок на сайте. Делать секцию для телефона и ссылки на сайт слишком избыточно. В качестве обёртки можно использовать `div`.

2022-01-28 19:07 UTC, andreysgra requested changes

2022-01-28 19:07 UTC, andreysgra commented on index.html
> +      </section>
[Это замечание](https://github.com/htmlacademy-htmlcss/1999403-sedona-33/pull/2#discussion_r793951473) относилось к двум секциям. Здесь секция тоже не нужна, замените на `div`.

2022-01-28 19:24 UTC, igorsokoltsov commented on index.html
> +        <button type="submit">Подписаться</button>
Не достаточно внимательно прочел комментарий. Все исправил.

2022-01-29 08:43 UTC, merged